language: node_js
node_js: 
  - 13

services: 
  - docker

script: 
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend emukungu/udagram-frontend:latest

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emukungu/udagram-frontend
